spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  profiles:
    active: slack #disable profile for local dev without Slack

slack.token: x
default-bot: dmn

zeebe:
  client:
    cloud:
      clusterId: x
      clientId: x
      clientSecret: x
      baseUrl: zeebe.ultrawombat.com
      region: bru-3
      authUrl: https://login.cloud.ultrawombat.com/oauth/token
#    broker:
#      gateway-address: "localhost:26500"
#    security:
#      plaintext: true

    job:
      timeout: PT30S

    worker:
      default-name: exploding-bpmn-app

logging:
  level:
    root: info
    io.camunda.zeebe.client: warn
    io.camunda.zeebe.client.job.poller: error
    io.zeebe.bpmn.games: info
    io.zeebe.bpmn.games.GameStateLogger: debug
    io.zeebe.bpmn.games.slack: warn
